---
- hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Atualizar lista de pacotes (apt-get update)
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Atualizar pacotes instalados (aptitude full-upgrade)
    ansible.builtin.apt:
      upgrade: full