source "${HOME}/antigen.zsh"
#source /usr/share/zsh/share/antigen.zsh # (Manjaro antigen-git)

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle fzf

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

# Load the theme.
antigen theme romkatv/powerlevel10k

# Tell Antigen that you're done.
antigen apply

# Aliases
# -------

# Prompt before overwrite or removal
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'

# ls
#alias ll='ls -lhFL' 
#alias la='ls -lhFLA'
#alias ltr='ls -lhFLtr'

# LSDeluxe
#alias l='lsd --group-dirs first'
#alias ll='lsd -lL --group-dirs first'
#alias la='lsd -lAL --group-dirs first'
#alias ltr='lsd -lLtr'

# LSDeluxe (no icons)
alias l='lsd -F --group-dirs first --icon never'
alias ll='lsd -lFL --group-dirs first --icon never'
alias la='lsd -lFLA --group-dirs first --icon never'
alias ltr='lsd -lFLtr --icon never'

# venv
alias myvenv='source ~/.venv/myvenv/bin/activate'
